version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./messages.db:/app/messages.db
      - ./services/message_factory/messages:/app/services/message_factory/messages
    environment:
      - DATABASE=sqlite
      - HOST_PORT=0.0.0.0:8000
      - AUTH_KEY=your_auth_key_here
    restart: unless-stopped